## ORB feature extraction using Kmeans

In [1]:
#packages,libraries and modules imported and used
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans

In [2]:
#Paths to images saved
folder1=r"C:\Users\francis\Desktop\2nd Semester\CV\CourseProject\Dataset\Dog"
folder2=r"C:\Users\francis\Desktop\2nd Semester\CV\CourseProject\Dataset\Cat"
folder3=r"C:\Users\francis\Desktop\2nd Semester\CV\CourseProject\Dataset\Cow"
folder4=r"C:\Users\francis\Desktop\2nd Semester\CV\CourseProject\Dataset\Goats"

In [3]:
#Feature extraction for Dog images 

for filename in os.listdir(folder1):
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #ORB feature extraction
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('ORB_dog.csv', mode='a', index=False)

In [4]:
#Feature vector of Dogs Dataset
data1= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB12\ORB_dog.csv',dtype='uint8')
data1=data1.astype(np.uint8)

#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0    1    2    3    4    5    6    7    8    9  ...   22   23   24  \
0      176  104  106   76   69  195  239   77  117  134  ...   48  202  115   
1      220   93   92  238   56  230   75  184  133    8  ...  121  189  243   
2      213    5   79  174   22  194  102   96  116   66  ...   13   30  240   
3      232   96   61  118   72   73  181  112  240  186  ...  242    2  197   
4       96  134   20  126  169  105   84   47  139   55  ...  203  145  155   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
50041   38  159  171  186  117  241  187  230  159   77  ...   58  245  107   
50042  153   93  127  253  182  214  127  242  181  236  ...   48  174  227   
50043  230   52  249   83  237  125  253   25  123  251  ...  251  194   79   
50044   42  189  169  155  253  245  159  239   31   95  ...  122  247  111   
50045  221  214  221  117   34   94   93  189  116  250  ...  109   10  242   

        25   26   27   28   29   30   31  
0      173  135    9   97  122  118  170  
1      235  162  144   58  179   32  112  
2      171  226   68   45  171  120    2  
3      227  117   57   64  113   71  171  
4      242   84  127   82   76  206   14  
...    ...  ...  ...  ...  ...  ...  ...  
50041   21  143  235  221   78  181  215  
50042  233  174  128   38  252  117  121  
50043   94  117  254  206  238  215  119  
50044   31  158  235  152   77  215  223  
50045  235  117  148   46  176  137  113  

[50046 rows x 32 columns]

In [5]:
#Feature extraction for Cat images 

for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #ORB feature extraction
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('ORB_cat.csv', mode='a', index=False)

In [6]:
#Feature vector of Cats Dataset
data2= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB12\ORB_cat.csv',dtype='uint8')
data2=data2.astype(np.uint8)

#shape
data2

0    1    2    3    4    5    6    7    8    9  ...   22   23   24  \
0        0  181   57   69   80   78   97   55  104   97  ...  113   15  101   
1      218  121  150  124  235  216   52   71  233   82  ...  146  105  179   
2      244  104  253  114  205   73   85  196  203  183  ...  250  226  219   
3      217   98  127  101    4   14  101  113  113  230  ...  181   14  211   
4      152  173   63  250   21  199  179  103  180    5  ...   50  125  251   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
50189  160   72  125   65  108  207  193   22   68   32  ...  113   10   71   
50190   25  217   83  236  146    6  207  255   36  200  ...   49   12  241   
50191  248   95  123  110   26  197   95  248  145  134  ...   58   63  243   
50192  119  239  238  166  254   18  190  237  216  230  ...  141  238  124   
50193  220  112  223  230   34   64  127   25   33  190  ...  175  128  210   

        25   26   27   28   29   30   31  
0      172   16    0   64   64  199  170  
1      243   86   43  106  116  171   31  
2      154   85   63  225  121   86  106  
3      233   97    4   99  160   98   98  
4      193  138   75  209    0  231  234  
...    ...  ...  ...  ...  ...  ...  ...  
50189  153   96   48   65  152   86  168  
50190  233  175  140   63  176  160  185  
50191  233   41  185  119   51   38  123  
50192   39  239  213  173  127  219  214  
50193  193  225  175   39  179   38   99  

[50194 rows x 32 columns]

In [7]:
#Feature extraction for Cow images 

for filename in os.listdir(folder3):
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #ORB feature extraction
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('ORB_cow.csv', mode='a', index=False)

In [8]:
#Feature vector of Cows Dataset
data3= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB12\ORB_cow.csv',dtype='uint8')
data3=data3.astype(np.uint8)

#shape
data3

0    1    2    3    4    5    6    7    8    9  ...   22   23   24  \
0       35   56  254   85  125   95  248   74  255  224  ...  243  200   31   
1       49  151   45   43  152  183  206  221  118   73  ...  127   21   37   
2       11  143  119  253  118  131  232   55   29    1  ...   37  223  238   
3       11  143   19  137  182  167  170  247   28    1  ...    4  255  172   
4      253  241  240   98  125   29   82  152   67  252  ...  248  144  219   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
50590  161  177   45    9  252  255  193   59   79  121  ...  121   21   79   
50591   86   33  249  231  170  108   94  155   42  161  ...  219   32  223   
50592   37  188  237   97  252  111  193  154   94  249  ...  255   16   79   
50593   77   59  185  164  186   44   91   19   42  237  ...  249    0  254   
50594   83  210  172  163  170   30  188  157  174  115  ...   31  213  134   

        25   26   27   28   29   30   31  
0      255   87   34  207  236   83  222  
1      109  162  196   89  222  248  244  
2      254  190  192   55  136  241  169  
3        6  190  192  150  206  161  169  
4      217    5  126   75  175   74   87  
...    ...  ...  ...  ...  ...  ...  ...  
50590   25  145  116   88  136  218  212  
50591  237   15   84  164  243  133   50  
50592   12   37  116  213  233   82  225  
50593  229   45  185  172  226   15   83  
50594  115  222  214   12   22  137   95  

[50595 rows x 32 columns]

In [9]:
#Feature extraction for goat images 

for filename in os.listdir(folder4):
    path=os.path.join(folder4,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #ORB feature extraction
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('ORB_goat.csv', mode='a', index=False)

In [10]:
#Feature vector of Cows Dataset
data4= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB12\ORB_goat.csv',dtype='uint8')
data4=data4.astype(np.uint8)

data4

0    1    2    3    4    5    6    7    8    9  ...   22   23   24  \
0      117   85   99  202  212  166   79  157   86  132  ...  125  142  253   
1       56  124   44   61  108  107   84   55   52  106  ...   65   31  230   
2      151  213   79   81  210  195  239  253  124  121  ...   13   86   44   
3      241  224  254  120   74  188   89   75  186   23  ...  242   17   83   
4       54  170  168   40   45  101  219  200  131  125  ...  250  145  219   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
50562  153   73   23  255   28  219   70  109   84    0  ...   97   61  177   
50563  231   54  253  103  224   46  123   24   57  254  ...  249  200  206   
50564  113  157  109  101  149   78   79  187   81  226  ...  121   15  249   
50565  205   54  245  103  160   62  123   24   41  254  ...  253  104  206   
50566  245   84  239  229   76  110   95  152  112  226  ...  249   10  215   

        25   26   27   28   29   30   31  
0      236  167   76  183  250  244  112  
1      231  120  177  124  252   26   91  
2       10  175  196  125  144  225  145  
3      171  112   61   97  192  206  194  
4       93  201  253  212  111   86  242  
...    ...  ...  ...  ...  ...  ...  ...  
50562  227   99   16  112   40  165  160  
50563  251  225  132  239  227   66  113  
50564  239  197   20  105  234   82   56  
50565  251   97  132  234  227   71  113  
50566  171  225   20   37  251  118   98  

[50567 rows x 32 columns]

In [11]:
#performing kmeans on each class
#Dog
kmeans1 = KMeans(n_clusters=5)
kmeans1.fit(data1)

#Cat
kmeans2 = KMeans(n_clusters=5)
kmeans2.fit(data2)

#cow
kmeans3 = KMeans(n_clusters=5)
kmeans3.fit(data3)

#Goat
kmeans4 = KMeans(n_clusters=5)
kmeans4.fit(data4)

KMeans(n_clusters=5)

In [12]:
#histograms of all the classes

hist1=np.histogram(kmeans1.labels_,bins=[0,1,2,3,4,5])
hist2=np.histogram(kmeans2.labels_,bins=[0,1,2,3,4,5])
hist3=np.histogram(kmeans3.labels_,bins=[0,1,2,3,4,5])
hist4=np.histogram(kmeans4.labels_,bins=[0,1,2,3,4,5])

print('histogram of Dogs')
print(hist1,"\n")

print('histogram of Cats')
print(hist2,"\n")

print('histogram of Cows')
print(hist3,"\n")

print('histogram of Goats')
print(hist4,"\n")

histogram of Dogs
(array([10439,  8801, 10378, 11116,  9312], dtype=int32), array([0, 1, 2, 3, 4, 5])) 

histogram of Cats
(array([ 9588, 10040, 10609, 10678,  9279], dtype=int32), array([0, 1, 2, 3, 4, 5])) 

histogram of Cows
(array([10521, 10279,  9027, 11038,  9730], dtype=int32), array([0, 1, 2, 3, 4, 5])) 

histogram of Goats
(array([ 9285, 11080, 10318,  9176, 10708], dtype=int32), array([0, 1, 2, 3, 4, 5])) 



In [13]:
#performing kmeans prediction of the entire Dog dataset with the pretrained kmeans model


#initialising i=0; as its the first class
i=0
data=[]

for filename in os.listdir(folder1):
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #ORB feature extraction
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans1.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('ORB_DogFinal.csv', mode='a', index=False)

In [14]:
#performing kmeans prediction of the entire Cat dataset with the pretrained kmeans model


#initialising i=1;
i=1
data=[]

for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #ORB feature extraction
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans2.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('ORB_CatFinal.csv', mode='a', index=False)

In [15]:
#performing kmeans prediction of the entire Cow dataset with the pretrained kmeans model


#initialising i=2;
i=2
data=[]

for filename in os.listdir(folder3):
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #ORB feature extraction
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans3.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('ORB_CowFinal.csv', mode='a', index=False)

In [16]:
#performing kmeans prediction of the entire Goats dataset with the pretrained kmeans model


#initialising i=3;
i=3
data=[]

for filename in os.listdir(folder4):
    path=os.path.join(folder4,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #ORB feature extraction
    orb = cv2.ORB_create()
    keypoints, descriptors = orb.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans4.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('ORB_GoatFinal.csv', mode='a', index=False)

In [17]:
#Displaying the kmeans predicted data
print("Dog")
dat1= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB12\ORB_DogFinal.csv')
print(dat1)

Dog
       0    1    2    3    4  Class
0     66  116  123  118   77      0
1    134   65  119  113   69      0
2    128   79   91   91  111      0
3    134   65  119  113   69      0
4     93  129  113   84   81      0
..   ...  ...  ...  ...  ...    ...
96    92   60   93  138  117      0
97   105   83  122   94   96      0
98    73  145   93   88  101      0
99    51  166  151   64   68      0
100   66  116  123  118   77      0

[101 rows x 6 columns]


In [18]:
print("Cat")
dat2= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB12\ORB_CatFinal.csv')
print(dat2)

Cat
       0    1    2    3    4  Class
0     46   60  173   44  177      1
1     80   81  129   78  132      1
2     73  174   98   54  101      1
3    105  104  105  107   79      1
4     94   61  135  115   95      1
..   ...  ...  ...  ...  ...    ...
96    81   88  124   89  118      1
97   125   93  107  110   65      1
98   104   94  110   88  104      1
99   106   78  126   71  119      1
100   47  119  104   88  142      1

[101 rows x 6 columns]


In [19]:
print("Cow")
dat3= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB12\ORB_CowFinal.csv')
print(dat3)

Cow
       0    1    2    3    4  Class
0    117  114  102  100   67      2
1    138   89   76   98   99      2
2    118  119   81  101   81      2
3    176  144   73   59   48      2
4    105   70   52  126  147      2
..   ...  ...  ...  ...  ...    ...
96   109   87   96  104  104      2
97   104  123   98   96   79      2
98   109  125  106   88   72      2
99    83   85  104  128  100      2
100  123   87   94  116   80      2

[101 rows x 6 columns]


In [20]:
print("Goat")
dat4= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB12\ORB_GoatFinal.csv')
print(dat4)

Goat
       0    1    2    3    4  Class
0    127  100   70   98  105      3
1     20   69  139  131  141      3
2    125  145   94   65   71      3
3    156  142   81   54   67      3
4     56   72   93  115  164      3
..   ...  ...  ...  ...  ...    ...
96   118  140   82   72   88      3
97   105  124   97   74  100      3
98   178  117   73   59   73      3
99   190  163   62   47   38      3
100  147  131   62   68   92      3

[101 rows x 6 columns]


In [21]:
#appending All classes into 1 csv file

A=dat1.append(dat2)
A=A.append(dat3)
A=A.append(dat4)

csv_data=A.to_csv('ORB_Final.csv', mode='a', index=False)

In [22]:
data= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB12\ORB_Final.csv')
data.columns=['1','2','3','4','5','Class']
#Total no of images = 404
data

1    2    3    4    5  Class
0     66  116  123  118   77      0
1    134   65  119  113   69      0
2    128   79   91   91  111      0
3    134   65  119  113   69      0
4     93  129  113   84   81      0
..   ...  ...  ...  ...  ...    ...
399  118  140   82   72   88      3
400  105  124   97   74  100      3
401  178  117   73   59   73      3
402  190  163   62   47   38      3
403  147  131   62   68   92      3

[404 rows x 6 columns]