## SIFT feature extraction using Kmeans

In [1]:
#packages,libraries and modules imported and used
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans

In [2]:
#Paths to images saved
folder1=r"C:\Users\francis\Desktop\2nd Semester\CV\CourseProject\Dataset\Dog"
folder2=r"C:\Users\francis\Desktop\2nd Semester\CV\CourseProject\Dataset\Cat"
folder3=r"C:\Users\francis\Desktop\2nd Semester\CV\CourseProject\Dataset\Cow"
folder4=r"C:\Users\francis\Desktop\2nd Semester\CV\CourseProject\Dataset\Goats"

In [3]:
#Feature extraction for Dog images 

for filename in os.listdir(folder1):
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('SIFT_dog.csv', mode='a', index=False)

In [4]:
#Feature vector of Dogs Dataset
data1= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB13\SIFT_dog.csv',dtype='uint8')
data1=data1.astype(np.uint8)

#shape
data1

0   1   2   3   4   5   6   7    8    9  ...  118  119  120  121  \
0        0   0   0   0   0   0   0   0    1   26  ...  118   80   16   20   
1       10  17  46  37  19  21  85  36    6    4  ...   10   28    5    0   
2        6   9   6  37  16   0   0   0   17   17  ...    7   27   32   25   
3        5   2   0   0   0   0   1   3   41   10  ...    4   21    8   14   
4       46  30   8   1   2   4  16  50  201  103  ...   20   37    8    4   
...     ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
169702  36  16  74  42   0   0   1   9    8   43  ...    5   32   33   55   
169703  11   2   4   5   2   3  10   8  118   14  ...    0    1   22   10   
169704   0   0   0   0   0   6  10   1  185   31  ...    2   15   67    0   
169705   0   0   0   0   0   0   0   0   96   48  ...    5   22    0    0   
169706   4  18  36  69  22   3  14   6   41   81  ...    0   18   37   24   

        122  123  124  125  126  127  
0        29   29   34   19   36   47  
1         1   15   12   10   44  100  
2       133   98   11    1    3   27  
3        44   53   29    3   13   35  
4         4    7    2    4   11    3  
...     ...  ...  ...  ...  ...  ...  
169702    9    0    0    3   32   40  
169703    1    3    9    2    1    2  
169704    0    0    0   16   21   17  
169705    1   21   17   11   12    0  
169706   27   17    1    0    1    3  

[169707 rows x 128 columns]

In [5]:
#Feature extraction for Cat images 

for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('SIFT_cat.csv', mode='a', index=False)

In [6]:
#Feature vector of Cats Dataset
data2= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB13\SIFT_cat.csv',dtype='uint8')
data2=data2.astype(np.uint8)

#shape
data2

0   1   2   3   4    5    6    7    8   9  ...  118  119  120  121  \
0        0   0   1   2  10  131   21    1   63   5  ...    2   11    2    7   
1       37   0   0   0  53   26    3   24  143   0  ...    0   16    9  101   
2        7   2   0   0   0    0    0    1   31   1  ...    1    2   10   33   
3        4   8  11   4   0    0  125   48    2   6  ...    0    0    0    0   
4       35  20   9  13  16   27   26   52   94  22  ...   42   24   16    2   
...     ..  ..  ..  ..  ..  ...  ...  ...  ...  ..  ...  ...  ...  ...  ...   
213933   0   0   0   0   0    0    0    0    5   1  ...   18   63    0    0   
213934  51   0   0   0   0    5   13  130   69   3  ...    0    0    1    0   
213935  55  35  40  26   7    0    0   11   50   8  ...    0    0    0   32   
213936   6   1   7  19  55  118   10    8   21   8  ...    0   11    8    4   
213937   0   0   0   0   0    0    0    0    0   1  ...    1    4    0   38   

        122  123  124  125  126  127  
0        79   16    0    0    0    0  
1       143   51   12    0    0    4  
2        96   57   23   18    1    1  
3         0    0    0    0    0    0  
4         0    0    0    2   12   12  
...     ...  ...  ...  ...  ...  ...  
213933    1  123  120    0    0    1  
213934    0    6   16    0    0    0  
213935   89    5    0    0    0    0  
213936    8   19    6    2    0    3  
213937  136   31    4    3    0    0  

[213938 rows x 128 columns]

In [7]:
#Feature extraction for Cow images 

for filename in os.listdir(folder3):
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('SIFT_cow.csv', mode='a', index=False)

In [8]:
#Feature vector of Cows Dataset
data3= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB13\SIFT_cow.csv',dtype='uint8')
data3=data3.astype(np.uint8)

#shape
data3

0  1  2   3    4   5    6   7    8   9  ...  118  119  120  121  122  \
0        0  0  0   0    0   0    0   0   32  27  ...    0   15   77   14    1   
1        0  0  0   1    0   0    2   0    3  11  ...   37   20   34   27   12   
2       32  6  1  28  111  43   31  66  142  14  ...    0    0    0    0    0   
3        5  3  2   5    6  27  108  30    6  12  ...   13    5    1    0    0   
4       37  8  0  13  114  60    4   8  137  64  ...    0    0   32   28    0   
...     .. .. ..  ..  ...  ..  ...  ..  ...  ..  ...  ...  ...  ...  ...  ...   
213549  24  0  0   0    0   0    0   3  197   1  ...    0   10   12   23    6   
213550  33  0  0   0    0   0    0   1  200  28  ...   13   51    4    9   11   
213551  30  1  0   0    0   0    0   2  205  19  ...   28   40    5    4    1   
213552  41  2  0   0    0   0    0   4  201  31  ...    8    4    0    8   60   
213553  51  7  0   0    0   0    0   0  202  71  ...   43   39    2    2    1   

        123  124  125  126  127  
0         1    2    1    0    3  
1        20    7   14   20   24  
2         0    0    0    0    0  
3         0    0    0    0    0  
4         0    0    0    0    0  
...     ...  ...  ...  ...  ...  
213549    0    0    0    1    1  
213550    2    1    1   16   14  
213551    1    2   11   16    5  
213552    4    1    5    6    2  
213553    0    0   24   65   23  

[213554 rows x 128 columns]

In [9]:
#Feature extraction for goat images 

for filename in os.listdir(folder4):
    path=os.path.join(folder4,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(512,512)
    img=cv2.resize(a,resize)#resize image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #append to the csv file
    csv_data=out.to_csv('SIFT_goat.csv', mode='a', index=False)

In [10]:
#Feature vector of Cows Dataset
data4= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB13\SIFT_goat.csv',dtype='uint8')
data4=data4.astype(np.uint8)

#shape
data4

0   1   2    3   4   5   6   7    8    9  ...  118  119  120  121  \
0         6  12  70   28  14  40  41  44   33   20  ...    1    1    1   10   
1       127  50  17    1   0   3   5  69   73   54  ...   34   25    1    0   
2         1  31  99  103   3   0   0   0   22   69  ...    6    5    0    5   
3         0   0   0    0   0   0   0   0   17   11  ...   10   21   35    4   
4       110  55   4    0   0   0   3  37  114  123  ...   12   20    0    0   
...     ...  ..  ..  ...  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
234048    0   0   0    0   0   0   0   0    2    1  ...    6   38  124    1   
234049    0   0   0    0   7  12   6   0   19    1  ...   18   14   96   26   
234050    0   0   2    0   0   0   4   0    1   10  ...    8   19   11   15   
234051    0   0   0    0   0   0  34   6   18    1  ...   16    6  118   64   
234052   33  24  20   32   7   9  20  51    8   10  ...    7   32    0    0   

        122  123  124  125  126  127  
0        33    0    0    0    0    1  
1         0    0    0    0    5    2  
2         1    0    0    0    0    0  
3        56   60    4    0    3  132  
4         0    0    0    0    0    0  
...     ...  ...  ...  ...  ...  ...  
234048    1   35   26    3    4   72  
234049   17    4    2    1    1   26  
234050   38   48   67    7    1    2  
234051   32   19   20    8    6   20  
234052    0    0    0    0    0    0  

[234053 rows x 128 columns]

In [11]:
#performing kmeans on each class
#Dog
kmeans1 = KMeans(n_clusters=5)
kmeans1.fit(data1)

#Cat
kmeans2 = KMeans(n_clusters=5)
kmeans2.fit(data2)

#cow
kmeans3 = KMeans(n_clusters=5)
kmeans3.fit(data3)

#Goat
kmeans4 = KMeans(n_clusters=5)
kmeans4.fit(data4)

KMeans(n_clusters=5)

In [12]:
#histograms of all the classes

hist1=np.histogram(kmeans1.labels_,bins=[0,1,2,3,4,5])
hist2=np.histogram(kmeans2.labels_,bins=[0,1,2,3,4,5])
hist3=np.histogram(kmeans3.labels_,bins=[0,1,2,3,4,5])
hist4=np.histogram(kmeans4.labels_,bins=[0,1,2,3,4,5])

print('histogram of Dogs')
print(hist1,"\n")

print('histogram of Cats')
print(hist2,"\n")

print('histogram of Cows')
print(hist3,"\n")

print('histogram of Goats')
print(hist4,"\n")

histogram of Dogs
(array([27212, 30818, 47792, 40678, 23207], dtype=int32), array([0, 1, 2, 3, 4, 5])) 

histogram of Cats
(array([55066, 63049, 30276, 35234, 30313], dtype=int32), array([0, 1, 2, 3, 4, 5])) 

histogram of Cows
(array([58900, 28841, 39738, 59156, 26919], dtype=int32), array([0, 1, 2, 3, 4, 5])) 

histogram of Goats
(array([53097, 33386, 66862, 38979, 41729], dtype=int32), array([0, 1, 2, 3, 4, 5])) 



In [13]:
#performing kmeans prediction of the entire Dog dataset with the pretrained kmeans model


#initialising i=0; as its the first class
i=0
data=[]

for filename in os.listdir(folder1):
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans1.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('SIFT_DogFinal.csv', mode='a', index=False)

In [14]:
#performing kmeans prediction of the entire Cat dataset with the pretrained kmeans model


#initialising i=1;
i=1
data=[]

for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans2.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('SIFT_CatFinal.csv', mode='a', index=False)

In [16]:
#performing kmeans prediction of the entire Cow dataset with the pretrained kmeans model


#initialising i=2;
i=2
data=[]

for filename in os.listdir(folder3):
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans3.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('SIFT_CowFinal.csv', mode='a', index=False)

In [17]:
#performing kmeans prediction of the entire Goats dataset with the pretrained kmeans model


#initialising i=3;
i=3
data=[]

for filename in os.listdir(folder4):
    path=os.path.join(folder4,filename)
    a=cv2.imread(path)
    resize=(512,512)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans4.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('SIFT_GoatFinal.csv', mode='a', index=False)

In [18]:
#Displaying the kmeans predicted data
print("Dog")
dat1= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB13\SIFT_DogFinal.csv')
print(dat1)

Dog
       0    1    2    3    4  Class
0    224  372  460  423  159      0
1    146  302  246  206  176      0
2    424  418  778  671  374      0
3    146  302  246  206  176      0
4    182  297  555  512  151      0
..   ...  ...  ...  ...  ...    ...
96   114  265  195  161   87      0
97   424  317  619  513  401      0
98   709  393  667  545  507      0
99    93  173  173  158   70      0
100  224  372  460  423  159      0

[101 rows x 6 columns]


In [19]:
print("Cat")
dat2= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB13\SIFT_CatFinal.csv')
print(dat2)

Cat
        0     1    2    3    4  Class
0     754  1058  325  382  598      1
1     658   751  450  579  637      1
2     909   944  356  499  495      1
3    1137  1286  714  867  563      1
4     568   938  267  407  284      1
..    ...   ...  ...  ...  ...    ...
96    267   301  115  131  266      1
97    129   154  124  145  234      1
98     76    97  116   99  227      1
99     70    87   39   40  181      1
100  1404  1532  594  854  515      1

[101 rows x 6 columns]


In [20]:
print("Cow")
dat3= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB13\SIFT_CowFinal.csv')
print(dat3)

Cow
        0    1    2     3    4  Class
0     478  147  432   298  222      2
1     584  236  535   524  339      2
2     343  122  399   207  173      2
3     421  273  382   444  308      2
4     697  386  532   685  332      2
..    ...  ...  ...   ...  ...    ...
96    253  116  155   277   59      2
97   2354  543  411  2460  609      2
98   1392  569  658  1265  582      2
99    963  717  900  1104  423      2
100   441  318  374   521  219      2

[101 rows x 6 columns]


In [21]:
print("Goat")
dat4= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB13\SIFT_GoatFinal.csv')
print(dat4)

Goat
        0     1     2    3     4  Class
0     955   418  1100  289   540      3
1     138    83   220  325   127      3
2     351   330   445  489   357      3
3    1613   903  1670  574   875      3
4     181   106   314  315   135      3
..    ...   ...   ...  ...   ...    ...
96    470   404   495  157   313      3
97   1417   785  1456  427   734      3
98    292   238   396  690   288      3
99   1573  1466  1922  310  1557      3
100  1785  1399  1956  517  1420      3

[101 rows x 6 columns]


In [22]:
#appending All classes into 1 csv file

A=dat1.append(dat2)
A=A.append(dat3)
A=A.append(dat4)

csv_data=A.to_csv('SIFT_Final.csv', mode='a', index=False)

In [24]:
data= pd.read_csv(r'C:\Users\francis\Desktop\2nd Semester\CV\Lab\CV_LAB13\SIFT_Final.csv')
data.columns=['1','2','3','4','5','Class']
#Total no of images = 404
data

1     2     3    4     5  Class
0     224   372   460  423   159      0
1     146   302   246  206   176      0
2     424   418   778  671   374      0
3     146   302   246  206   176      0
4     182   297   555  512   151      0
..    ...   ...   ...  ...   ...    ...
399   470   404   495  157   313      3
400  1417   785  1456  427   734      3
401   292   238   396  690   288      3
402  1573  1466  1922  310  1557      3
403  1785  1399  1956  517  1420      3

[404 rows x 6 columns]